// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/atelier/TypographyOnly.tsx": () => import("../components/mockups/atelier/TypographyOnly.tsx"),
  "./components/mockups/atelier-ai/AIImagery.tsx": () => import("../components/mockups/atelier-ai/AIImagery.tsx")
};
